name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 7
      - uses: actions/setup-node@v4
        with:
          node-version: v21.3.0
          cache: 'npm'

      - run: npm install --frozen-lockfile
      - run: npm run ci
